# -*- coding: utf-8 -*-
"""Maria_Fernanda_19203744_prob2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFqVPsde5k4AF2r5iKqKqvIWhIR0WCrU

#Problema 2:

## Considere os sistemas lineares abaixo:
$$
 a) \left\{
\begin{array}{*{4}{rC}
l}2x1 - x2 + x3 - x4 = 6 \\
x2 - x3 + x4 = 5\\
x4 = 5 \\
x3 - x4 = 3
\end{array}
\right.
\\
b) \left\{
\begin{array}{*{3}{rC}
l}x2 + 2x3 = 4 \\
x1 - x2 + x3 = 6 \\
x1 - x3 = 2 \\
\end{array}
\right.
\\
c) \left\{
\begin{array}{*{4}{rC}
l} 2x1 = 3 \\
x1 + 1.5x2 = 4.5 \\
- 3x2 + 0.5x3 = - 6.6 \\
2x1 - 2x2 + x3 + x4 = 0.8
\end{array}
\right.
\\
$$

### 1- Use o método de Gauss ou apenas trocas de linhas/ colunas para transformar os sistemas acima em sistemas triangulares.

$$
\displaystyle{a)\left(\begin{array}{ccccc}
2 & -1 & 1 & -1 & 6\\
0 & 1 & -1 & 1 & 5\\
0 & 0 & 0 & 1 & 5\\
0 & 0 & 1 & -1 & 3\\
\end{array}\right)}
\\
$$
$$
\\
L_3 ← L_4:
\\
\displaystyle{\left(\begin{array}{ccccc}
2 & -1 & 1 & -1 & 6\\
0 & 1 & -1 & 1 & 5\\
0 & 0 & 1 & -1 & 3\\
0 & 0 & 0 & 1 & 5\\
\end{array}\right)}
\\
x_4 = 5 \\
x_3 = 8 = x_2  \\
x1 = \frac{11}{2}
$$

$$
\displaystyle{b)\left(\begin{array}{cccc}
1 & -1 & 1 & 6 \\
0 & 1 & 2 & 4 \\
1 & 0 & -1 & 2 \\
\end{array}\right)}
\\
$$
$$
\\
L_3 ← L_3 - L1:
\\
\displaystyle{\left(\begin{array}{cccc}
1 & -1 & 1 & 6 \\
0 & 1 & 2 & 4 \\
0 & 1 & -2 & -4 \\
\end{array}\right)}
\\
L_3 ← L_3 - L_2:
\\
\displaystyle{\left(\begin{array}{cccc}
1 & -1 & 1 & 6 \\
0 & 1 & 2 & 4 \\
0 & 0 & -1 & -8 \\
\end{array}\right)}
\\
x_3 = 2\\ x_2 = 0 \\ x_1 = 4
$$

$$
\displaystyle{c)\left(\begin{array}{ccccc}
2 & 0 & 0 & 0 & 3\\
1 & 1.5 & 0 & 0 & 4.5\\
0 & -3 & 0.5 & 0 & -6.6\\
2 & -2 & 1 & 1 & 0.8\\
\end{array}\right)}
\\
L_1 ⟷ L_3:
\\
\displaystyle{\left(\begin{array}{ccccc}
2 & -2 & 1 & 1 & 0.8\\
1 & 1.5 & 0 & 0 & 4.5\\
2 & 0 & 0 & 0 & 3\\
0 & -3 & 0.5 & 0 & -6.6\\
\end{array}\right)}
\\
x_1 = \frac3{2}
\\
L_2 ← 2 × L_2 - L_3:
\\
\displaystyle{\left(\begin{array}{ccccc}
2 & -2 & 1 & 1 & 0.8\\
0 & 3 & 0 & 0 & 6\\
2 & 0 & 0 & 0 & 3\\
0 & -3 & 0.5 & 0 & -6.6\\
\end{array}\right)}
\\
x_2 = 2 \\ L_2 ⟷ L_3: \\
\displaystyle{\left(\begin{array}{ccccc}
2 & -2 & 1 & 1 & 0.8\\
2 & 0 & 0 & 0 & 3\\
0 & 3 & 0 & 0 & 6\\
0 & -3 & 0.5 & 0 & -6.6\\
\end{array}\right)}
\\
L_4 ← L_4 + L_3: \\
\displaystyle{\left(\begin{array}{ccccc}
2 & -2 & 1 & 1 & 0.8\\
2 & 0 & 0 & 0 & 3\\
0 & 3 & 0 & 0 & 6\\
0 & 0 & 0.5 & 0 & -0.6\\
\end{array}\right)}
\\
x_3 = -\frac6{5} \\ x_4 = 3
$$

### 2- Implemente o método da substituição inversa para solucionar sistemas de tamanho $n$ ($n$ incógnitas e $n$ equações).
"""

import numpy as np
# Recebe uma matriz A e um vetor das soluções b
def inversa(A, b):
    n = len(b)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
      # np.sum() implementa um somatório.
        soma = np.sum(A[i, i + 1:] * x[i + 1:])
        x[i] = (b[i] - soma) / A[i, i]

    return x

"""### 3 - Resolva numericamente os sistemas usando o método implementado no item 2.

### Sistema $a)$
"""

A = np.array([[2,-1,1,-1],
    [0,1,-1,1],
    [0,0,1,-1],
    [0,0,0,1]])
b = np.array([6,5,3,5])
sol = inversa(A,b)
print("a)")
for i in range(len(sol)):
    print(f"x[{i}] = {sol[i]}")

"""### Sistema $b)$"""

A = np.array([
    [1,  -1, 1],
    [0, 1, 2],
    [1,  0, 1]
])
b = np.array([6,4,2])
sol = inversa(A,b)
print("a)")
for i in range(len(sol)):
    print(f"x[{i}] = {sol[i]}")