# -*- coding: utf-8 -*-
"""Maria_Fernanda_19203744_prob1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jTmZiog8tDMSGI4vZvXMoyVlFManaK-9

##Problema 1
Queremos determinar o volume $V$ ocupado por um gás à temperatura $T$
e pressão $p$. A equação de estado (isto é, a equaçao que relaciona $p, V$ e $T$)
é dada por:
# $$ \biggr[
p + a \left( \frac N{V} \right)^2
\biggr]
(V - Nb) = kNT
$$
Para dióxido de carbono:
$$\begin{equation}
a = 0,401Pa
\end{equation}$$ e
$$\begin{equation}
b = 24,7\times 10^{-6} m^3
\end{equation}$$ A constante de Boltzman é $k = 1,3806503\times10^{-23} K^{-1}$

Determine o volume ocupado por 1000 moléculas de $CO_{2}$ à $T$ = 300 k e pressão $p = 3,5 \times 10^7$ Pa.

Usar Método de Newton para determinar $V$ com tolerância de $10^{-6}$.
Sugestão: reescrever equação na forma $f(V) = 0$ e determine $f'(V)$.

##$f'(V) = \frac {-40100V + 19809.4}{V³} + 35000000$
"""

def f(V):
    return (3.5e7 + 0.401 * (1000/V)**2) * (V - 1000*24.7e-6) - 1000*1.3806503e-23*300

def df(V):
    return (3.5e7 + 0.401 * (1000/V)**2) - 2*0.401*(1000**2)*(V**-3)*(V - 1000*24.7e-6) - (1000*24.7e-6)*2*0.401*(1000/V)**2

def newton(v0):
  tolerancia = 10**(-6)
  n = 100
  i = 0
  v = v0
  erro = 1
  while(erro > tolerancia and i < n):
        vi = v - (f(v)/df(v))
        erro = abs(vi -v)
        i+=1
        v = vi
        print('Iteração: {} \nValor atual: {} \nErro: {}\n'.format(i,v,erro))
  return v

"""### Foi escolhido um chute inicial $V_0$ próximo da solução dada por *software* de cálculo."""

V0 = 0.03  # Estimativa inicial para o volume
print(newton(V0))